---
- hosts: debians
  become: true
  become_user: root
  tasks:
    - name: Update repositorio apt y cache en todos los Debian/Ubuntu
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade  de todos los paquetes en los servers
      apt: upgrade=dist force_apt_get=yes

    - name: Chequear si un reinicio es necesario en los servidores
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reiniciar el servidor si es requerido
      reboot:
        msg: "Reboot iniciado por Ansible por kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
